[package]
name = "handler"
version = "0.1.0"
authors = ["drskur"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
mongodb = "2.0.0-alpha.1"
serde = "1"
serde_yaml = "0.8"
futures = "0.3"
bytes = "1"